org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=false
android.nonTransitiveRClass=true

# Current test target from your log. For a physical ARM64 phone change to:
# droidxAbis=arm64-v8a
# To package both (larger APK/build download): droidxAbis=x86_64,arm64-v8a
droidxAbis=x86_64
