package com.droidx;

final class DemoTemplates {
    private DemoTemplates() {}

    static final String CONSOLE_SAMPLE = String.join("\n",
            "#include <iostream>",
            "#include <string>",
            "",
            "int main() {",
            "    std::string name = \"DroidCompiler\";",
            "    std::cout << \"Hello from \" << name << \"!\\n\";",
            "    std::cout << \"2 + 3 = \" << (2 + 3) << \"\\n\";",
            "    return 0;",
            "}") + "\n";

    static final String SDL_GLES_TOUCH_SAMPLE = String.join("\n",
            "#include <SDL2/SDL.h>",
            "#include <GLES3/gl3.h>",
            "#include <algorithm>",
            "#include <cstdio>",
            "",
            "static GLuint compileShader(GLenum type, const char* src) {",
            "    GLuint s = glCreateShader(type);",
            "    glShaderSource(s, 1, &src, nullptr);",
            "    glCompileShader(s);",
            "    GLint ok = GL_FALSE;",
            "    glGetShaderiv(s, GL_COMPILE_STATUS, &ok);",
            "    if (!ok) {",
            "        char log[1024] = {};",
            "        glGetShaderInfoLog(s, sizeof(log), nullptr, log);",
            "        SDL_Log(\"Shader compile error: %s\", log);",
            "        glDeleteShader(s);",
            "        return 0;",
            "    }",
            "    return s;",
            "}",
            "",
            "static GLuint createProgram() {",
            "    const char* vs = R\"(#version 300 es",
            "layout(location=0) in vec2 aPos;",
            "uniform vec2 uOffset;",
            "void main() {",
            "    gl_Position = vec4(aPos * 0.34 + uOffset, 0.0, 1.0);",
            "}",
            ")\";",
            "    const char* fs = R\"(#version 300 es",
            "precision mediump float;",
            "uniform vec3 uColor;",
            "out vec4 fragColor;",
            "void main() {",
            "    fragColor = vec4(uColor, 1.0);",
            "}",
            ")\";",
            "    GLuint v = compileShader(GL_VERTEX_SHADER, vs);",
            "    GLuint f = compileShader(GL_FRAGMENT_SHADER, fs);",
            "    if (!v || !f) return 0;",
            "    GLuint p = glCreateProgram();",
            "    glAttachShader(p, v);",
            "    glAttachShader(p, f);",
            "    glLinkProgram(p);",
            "    glDeleteShader(v);",
            "    glDeleteShader(f);",
            "    GLint ok = GL_FALSE;",
            "    glGetProgramiv(p, GL_LINK_STATUS, &ok);",
            "    if (!ok) {",
            "        char log[1024] = {};",
            "        glGetProgramInfoLog(p, sizeof(log), nullptr, log);",
            "        SDL_Log(\"Program link error: %s\", log);",
            "        glDeleteProgram(p);",
            "        return 0;",
            "    }",
            "    return p;",
            "}",
            "",
            "int main(int argc, char** argv) {",
            "    (void)argc; (void)argv;",
            "    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS) != 0) {",
            "        SDL_Log(\"SDL_Init failed: %s\", SDL_GetError());",
            "        return 1;",
            "    }",
            "",
            "    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);",
            "    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);",
            "    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);",
            "    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);",
            "    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);",
            "",
            "    SDL_Window* window = SDL_CreateWindow(",
            "        \"DroidCompiler GLES3 + Touch\",",
            "        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,",
            "        1280, 720, SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_RESIZABLE);",
            "    if (!window) {",
            "        SDL_Log(\"SDL_CreateWindow failed: %s\", SDL_GetError());",
            "        SDL_Quit();",
            "        return 2;",
            "    }",
            "",
            "    SDL_GLContext ctx = SDL_GL_CreateContext(window);",
            "    if (!ctx) {",
            "        SDL_Log(\"SDL_GL_CreateContext failed: %s\", SDL_GetError());",
            "        SDL_DestroyWindow(window);",
            "        SDL_Quit();",
            "        return 3;",
            "    }",
            "    SDL_GL_SetSwapInterval(1);",
            "",
            "    SDL_Log(\"GL_VERSION: %s\", (const char*)glGetString(GL_VERSION));",
            "    SDL_Log(\"GL_RENDERER: %s\", (const char*)glGetString(GL_RENDERER));",
            "",
            "    GLuint program = createProgram();",
            "    if (!program) return 4;",
            "",
            "    const GLfloat vertices[] = {",
            "         0.0f,  0.80f,",
            "        -0.72f, -0.55f,",
            "         0.72f, -0.55f",
            "    };",
            "    GLuint vao = 0, vbo = 0;",
            "    glGenVertexArrays(1, &vao);",
            "    glBindVertexArray(vao);",
            "    glGenBuffers(1, &vbo);",
            "    glBindBuffer(GL_ARRAY_BUFFER, vbo);",
            "    glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);",
            "    glEnableVertexAttribArray(0);",
            "    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(GLfloat), nullptr);",
            "",
            "    GLint uOffset = glGetUniformLocation(program, \"uOffset\");",
            "    GLint uColor = glGetUniformLocation(program, \"uColor\");",
            "    float touchX = 0.0f;",
            "    float touchY = 0.0f;",
            "    float pressure = 0.0f;",
            "    bool touching = false;",
            "    bool running = true;",
            "",
            "    while (running) {",
            "        SDL_Event e;",
            "        while (SDL_PollEvent(&e)) {",
            "            if (e.type == SDL_QUIT) running = false;",
            "            if (e.type == SDL_KEYDOWN && e.key.keysym.sym == SDLK_ESCAPE) running = false;",
            "            if (e.type == SDL_FINGERDOWN || e.type == SDL_FINGERMOTION) {",
            "                touching = true;",
            "                touchX = std::clamp(e.tfinger.x * 2.0f - 1.0f, -0.72f, 0.72f);",
            "                touchY = std::clamp(1.0f - e.tfinger.y * 2.0f, -0.72f, 0.72f);",
            "                pressure = e.tfinger.pressure;",
            "            }",
            "            if (e.type == SDL_FINGERUP) {",
            "                touching = false;",
            "                pressure = 0.0f;",
            "            }",
            "        }",
            "",
            "        int w = 0, h = 0;",
            "        SDL_GL_GetDrawableSize(window, &w, &h);",
            "        glViewport(0, 0, w, h);",
            "        glClearColor(0.035f, 0.045f, 0.07f, 1.0f);",
            "        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);",
            "",
            "        glUseProgram(program);",
            "        glUniform2f(uOffset, touchX, touchY);",
            "        if (touching) {",
            "            glUniform3f(uColor, 0.25f + 0.70f * pressure, 0.85f, 0.38f);",
            "        } else {",
            "            glUniform3f(uColor, 0.35f, 0.58f, 1.0f);",
            "        }",
            "        glBindVertexArray(vao);",
            "        glDrawArrays(GL_TRIANGLES, 0, 3);",
            "        SDL_GL_SwapWindow(window);",
            "    }",
            "",
            "    glDeleteBuffers(1, &vbo);",
            "    glDeleteVertexArrays(1, &vao);",
            "    glDeleteProgram(program);",
            "    SDL_GL_DeleteContext(ctx);",
            "    SDL_DestroyWindow(window);",
            "    SDL_Quit();",
            "    return 0;",
            "}") + "\n";

    static final String NETWORK_SAMPLE = String.join("\n",
            "#include <curl/curl.h>",
            "#include <algorithm>",
            "#include <sys/socket.h>",
            "#include <netinet/in.h>",
            "#include <arpa/inet.h>",
            "#include <netdb.h>",
            "#include <poll.h>",
            "#include <unistd.h>",
            "#include <cerrno>",
            "#include <cstring>",
            "#include <iostream>",
            "#include <string>",
            "",
            "#ifndef DROIDX_CA_BUNDLE",
            "#define DROIDX_CA_BUNDLE \"\"",
            "#endif",
            "",
            "static size_t writeCb(char* ptr, size_t size, size_t nmemb, void* userdata) {",
            "    auto* out = static_cast<std::string*>(userdata);",
            "    out->append(ptr, size * nmemb);",
            "    return size * nmemb;",
            "}",
            "",
            "static void configureTls(CURL* c) {",
            "    if (DROIDX_CA_BUNDLE[0] != '\\0') {",
            "        curl_easy_setopt(c, CURLOPT_CAINFO, DROIDX_CA_BUNDLE);",
            "    }",
            "    curl_easy_setopt(c, CURLOPT_SSL_VERIFYPEER, 1L);",
            "    curl_easy_setopt(c, CURLOPT_SSL_VERIFYHOST, 2L);",
            "}",
            "",
            "static bool testHttps() {",
            "    CURL* c = curl_easy_init();",
            "    if (!c) return false;",
            "    std::string body;",
            "    curl_easy_setopt(c, CURLOPT_URL, \"https://postman-echo.com/get?source=droidcompiler\");",
            "    curl_easy_setopt(c, CURLOPT_FOLLOWLOCATION, 1L);",
            "    curl_easy_setopt(c, CURLOPT_CONNECTTIMEOUT, 8L);",
            "    curl_easy_setopt(c, CURLOPT_TIMEOUT, 12L);",
            "    curl_easy_setopt(c, CURLOPT_WRITEFUNCTION, writeCb);",
            "    curl_easy_setopt(c, CURLOPT_WRITEDATA, &body);",
            "    configureTls(c);",
            "    CURLcode rc = curl_easy_perform(c);",
            "    long http = 0;",
            "    curl_easy_getinfo(c, CURLINFO_RESPONSE_CODE, &http);",
            "    std::cout << \"HTTPS: \" << curl_easy_strerror(rc)",
            "              << \" HTTP=\" << http << \" bytes=\" << body.size() << \"\\n\";",
            "    curl_easy_cleanup(c);",
            "    return rc == CURLE_OK && http >= 200 && http < 400;",
            "}",
            "",
            "static bool testTcp() {",
            "    addrinfo hints{};",
            "    hints.ai_socktype = SOCK_STREAM;",
            "    hints.ai_family = AF_UNSPEC;",
            "    addrinfo* list = nullptr;",
            "    int gai = getaddrinfo(\"example.com\", \"80\", &hints, &list);",
            "    if (gai != 0) {",
            "        std::cout << \"TCP DNS failed: \" << gai_strerror(gai) << \"\\n\";",
            "        return false;",
            "    }",
            "    int fd = -1;",
            "    for (addrinfo* p = list; p; p = p->ai_next) {",
            "        fd = socket(p->ai_family, p->ai_socktype, p->ai_protocol);",
            "        if (fd >= 0 && connect(fd, p->ai_addr, p->ai_addrlen) == 0) break;",
            "        if (fd >= 0) close(fd);",
            "        fd = -1;",
            "    }",
            "    freeaddrinfo(list);",
            "    if (fd < 0) {",
            "        std::cout << \"TCP connect failed errno=\" << errno << \"\\n\";",
            "        return false;",
            "    }",
            "    const char req[] = \"HEAD / HTTP/1.1\\r\\nHost: example.com\\r\\nConnection: close\\r\\n\\r\\n\";",
            "    ssize_t sent = send(fd, req, sizeof(req) - 1, 0);",
            "    pollfd pfd{fd, POLLIN, 0};",
            "    int pr = poll(&pfd, 1, 4000);",
            "    char buf[256] = {};",
            "    ssize_t got = pr > 0 ? recv(fd, buf, sizeof(buf) - 1, 0) : -1;",
            "    close(fd);",
            "    std::cout << \"TCP: sent=\" << sent << \" recv=\" << got;",
            "    if (got > 0) std::cout << \" first='\" << std::string(buf, (size_t)std::min<ssize_t>(got, 60)) << \"'\";",
            "    std::cout << \"\\n\";",
            "    return sent > 0 && got > 0;",
            "}",
            "",
            "static bool testUdpDns() {",
            "    int fd = socket(AF_INET, SOCK_DGRAM, 0);",
            "    if (fd < 0) return false;",
            "    sockaddr_in dst{};",
            "    dst.sin_family = AF_INET;",
            "    dst.sin_port = htons(53);",
            "    inet_pton(AF_INET, \"1.1.1.1\", &dst.sin_addr);",
            "    const unsigned char q[] = {",
            "        0x12,0x34, 0x01,0x00, 0x00,0x01, 0x00,0x00, 0x00,0x00, 0x00,0x00,",
            "        0x07,'e','x','a','m','p','l','e', 0x03,'c','o','m', 0x00,",
            "        0x00,0x01, 0x00,0x01",
            "    };",
            "    ssize_t sent = sendto(fd, q, sizeof(q), 0, (sockaddr*)&dst, sizeof(dst));",
            "    pollfd pfd{fd, POLLIN, 0};",
            "    int pr = poll(&pfd, 1, 3000);",
            "    unsigned char reply[512];",
            "    ssize_t got = pr > 0 ? recvfrom(fd, reply, sizeof(reply), 0, nullptr, nullptr) : -1;",
            "    close(fd);",
            "    std::cout << \"UDP DNS: sent=\" << sent << \" recv=\" << got << \"\\n\";",
            "    return sent == (ssize_t)sizeof(q) && got > 12;",
            "}",
            "",
            "static bool waitSocket(CURL* c, short events, int timeoutMs) {",
            "    curl_socket_t sock = CURL_SOCKET_BAD;",
            "    if (curl_easy_getinfo(c, CURLINFO_ACTIVESOCKET, &sock) != CURLE_OK || sock == CURL_SOCKET_BAD) return false;",
            "    pollfd pfd{(int)sock, events, 0};",
            "    return poll(&pfd, 1, timeoutMs) > 0;",
            "}",
            "",
            "static bool testWebSocket() {",
            "    CURL* c = curl_easy_init();",
            "    if (!c) return false;",
            "    curl_easy_setopt(c, CURLOPT_URL, \"wss://ws.postman-echo.com/raw\");",
            "    curl_easy_setopt(c, CURLOPT_CONNECT_ONLY, 2L);",
            "    curl_easy_setopt(c, CURLOPT_CONNECTTIMEOUT, 8L);",
            "    curl_easy_setopt(c, CURLOPT_TIMEOUT, 12L);",
            "    configureTls(c);",
            "    CURLcode rc = curl_easy_perform(c);",
            "    if (rc != CURLE_OK) {",
            "        std::cout << \"WebSocket connect: \" << curl_easy_strerror(rc) << \"\\n\";",
            "        curl_easy_cleanup(c);",
            "        return false;",
            "    }",
            "",
            "    const std::string msg = \"hello from DroidCompiler\";",
            "    size_t offset = 0;",
            "    while (offset < msg.size()) {",
            "        size_t sent = 0;",
            "        rc = curl_ws_send(c, msg.data() + offset, msg.size() - offset, &sent, 0, CURLWS_TEXT);",
            "        offset += sent;",
            "        if (rc == CURLE_AGAIN) {",
            "            if (!waitSocket(c, POLLOUT, 3000)) break;",
            "            rc = CURLE_OK;",
            "            continue;",
            "        }",
            "        if (rc != CURLE_OK) break;",
            "    }",
            "    if (rc != CURLE_OK || offset != msg.size()) {",
            "        std::cout << \"WebSocket send: \" << curl_easy_strerror(rc) << \" sent=\" << offset << \"\\n\";",
            "        curl_easy_cleanup(c);",
            "        return false;",
            "    }",
            "",
            "    char buf[1024];",
            "    size_t got = 0;",
            "    const curl_ws_frame* meta = nullptr;",
            "    for (int i = 0; i < 20; ++i) {",
            "        rc = curl_ws_recv(c, buf, sizeof(buf), &got, &meta);",
            "        if (rc == CURLE_AGAIN) {",
            "            if (!waitSocket(c, POLLIN, 250)) continue;",
            "            continue;",
            "        }",
            "        break;",
            "    }",
            "    bool ok = rc == CURLE_OK && got > 0;",
            "    std::cout << \"WebSocket: \" << curl_easy_strerror(rc) << \" recv=\" << got;",
            "    if (ok) std::cout << \" payload='\" << std::string(buf, got) << \"'\";",
            "    std::cout << \"\\n\";",
            "    curl_easy_cleanup(c);",
            "    return ok;",
            "}",
            "",
            "int main() {",
            "    curl_global_init(CURL_GLOBAL_DEFAULT);",
            "    const curl_version_info_data* vi = curl_version_info(CURLVERSION_NOW);",
            "    std::cout << \"libcurl: \" << (vi && vi->version ? vi->version : \"unknown\") << \"\\n\";",
            "    std::cout << \"CA bundle: \" << DROIDX_CA_BUNDLE << \"\\n\";",
            "",
            "    bool https = testHttps();",
            "    bool tcp = testTcp();",
            "    bool udp = testUdpDns();",
            "    bool ws = testWebSocket();",
            "",
            "    std::cout << \"\\nRESULTS https=\" << https",
            "              << \" tcp=\" << tcp",
            "              << \" udp=\" << udp",
            "              << \" websocket=\" << ws << \"\\n\";",
            "    curl_global_cleanup();",
            "    return 0;",
            "}") + "\n";

}
